services:
    - docker

before_install:
    - docker pull carlad/sinatra

script:
    - docker run --rm -it --mount "type=bind,src=$(pwd),dst=/host" fedora "/bin/bash /host/scripts/build_sed_full.sh"
